### ISSUE TITLE
GD won't load when I updated HT

### ISSUE THREAD

**Issue by GeorgeDash** [Alphalaneous/HappyTextures#29] opened 2024-12-15 09:49 UTC
So I just opened Geometry Dash and I saw in the Geode menu that **Happy Textures** had an update, so I updated it. However, when I clicked on the "Restart Mods" button (or whatever it says), the game shows black screen with the cursor loading, and... it's stuck.
And the weirdest part is (as you'll see in the video) that Geode doesn't crash, but the game _itself_ stops responding when I start spamming the left-click button on the mouse.
I tried verify the integrity of the files and the only thing it showed was that 2 files weren't verified... and that's it.

Here's a short video with the problem:
https://github.com/user-attachments/assets/7ffc45e6-41c7-4d14-92a9-860c02cb313d

**Comment by Alphalaneous** [comment] 2024-12-15 09:58
I will look into this. Thank you for your report

**Comment by Alphalaneous** [comment] 2024-12-15 10:01
Can you provide some extra information such as your geometry dash path and geometry dash appdata path?

**Comment by GeorgeDash** [comment] 2024-12-15 10:07
Absolutely!
My GD path is: 
_D:\Steam\steamapps\common\Geometry Dash\GeometryDash.exe_
and my GD AppData path is:
_C:\Users\username\AppData\Local\GeometryDash_

**Comment by Alphalaneous** [comment] 2024-12-15 10:14
Thank you, secondly, does your username in the appdata path contain any special characters (non-alphanumeric)

**Comment by GeorgeDash** [comment] 2024-12-15 10:15
No, it contains only letters.

**Comment by Alphalaneous** [comment] 2024-12-15 10:16
Thank you

**Comment by Alphalaneous** [comment] 2024-12-15 10:18
I think I know where the issue is. Tomorrow if you don’t mind, would you be willing to test some versions of Happy Textures for me on discord? My username is Alphalaneous

**Comment by GeorgeDash** [comment] 2024-12-15 10:19
OK, but I'll have to see if I have time - it's not a big problem that I can't play GD, if you get me.

**Comment by Alphalaneous** [comment] 2024-12-15 10:22
Alright. Also, to remove the mod for the time being, you can open geode in safe mode by holding shift before launching the game, and then remove the mod

**Comment by GeorgeDash** [comment] 2024-12-15 10:23
OK, thanks for your help! I really appreciate it! 😊

**Comment by GeorgeDash** [comment] 2024-12-15 10:23
Also, I've sent you a friend request on Discord - my user is GeorgeCraft225.

**Comment by GeorgeDash** [comment] 2024-12-15 10:24
And last quesiton - do I uninstall or just disable the mod?

**Comment by Alphalaneous** [comment] 2024-12-15 10:24
Either option works

**Comment by Alphalaneous** [comment] 2024-12-15 18:56
Likely fixed in 1.7.1

**Closed by Alphalaneous** 2024-12-15 18:56 UTC
